#!/bin/bash

echo "Use CMake"

mkdir -p BUILD/cli
mkdir -p BUILD/gui

cd BUILD/cli
cmake ../..
make
sudo make install

cd ../gui
cmake ../..
make
sudo make install
cd ../..


# SCRIPTS="${SCRIPTS} ${PWD}/src/zdmadm"
# SCRIPTS="${SCRIPTS} ${PWD}/src/zdm-status"
# SCRIPTS="${SCRIPTS} ${PWD}/src/zdm-zones"
# SCRIPTS="${SCRIPTS} ${PWD}/src/zdm-mlog"
# SCRIPTS="${SCRIPTS} ${PWD}/zdmonitor/zdmon"
#
# INSTALL_TO="${HOME}/bin"
#
# if [[ ! -d ${INSTALL_TO} ]]; then
# 	echo ${INSTALL_TO} not found. Creating.
# 	mkdir ${INSTALL_TO}
# fi
#
# if [[ -d ${INSTALL_TO} ]]; then
# 	echo Installing ${SCRIPTS} to ${INSTALL_TO} ...
# 	cd ${INSTALL_TO}
# fi
#
# echo Installing scripts to ${INSTALL_TO}
# for i in ${SCRIPTS}
# do
# 	echo ln -sf ${i} ~/bin/.
# 	ln -sf ${i} .
# done
#
